export default [
    {
        code: 'javascript',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/js.svg',
        url: 'https://www.javascript.com',
        name: 'JavaScript',
        tooltip: 'Knowledge level',
        description:
            'I started developing in JavaScript in 2017, thanks to the continuous improvements of this language I can now exploit its potential.',
    },
    {
        code: 'npmjs',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/npm.svg',
        url: 'https://www.npmjs.com',
        name: 'npm',
        tooltip: 'Knowledge level',
        description: 'It is mandatory to be able to use npm before starting to work with Node.js or React.',
    },
    {
        code: 'eslint',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/eslint.svg',
        url: 'https://eslint.org',
        name: 'ESLint',
        tooltip: 'Knowledge level',
        description: 'It is impossible to develop without it. Since I started using JavaScript ESLint is my inseparable tool.',
    },
    {
        code: 'nodejs',
        enabled: true,
        main: true,
        level: 4,
        imageUrl: '/logos/nodejs.svg',
        url: 'https://nodejs.org',
        name: 'Node.js',
        tooltip: 'Knowledge level',
        description: 'Starting from the end of 2017 Node.js has supported Java as back-end technology in my developer life.',
    },
    {
        code: 'feathersjs',
        enabled: true,
        main: true,
        level: 4,
        imageUrl: '/logos/feathersjs.svg',
        url: 'https://feathersjs.com',
        name: 'Feathers',
        tooltip: 'Knowledge level',
        description:
            'I always use Node.js with Feathers. Like Spring for Java, Feathers is a framework to simplify the development of REST APIs in Node.js.',
    },
    {
        code: 'react',
        enabled: true,
        main: true,
        level: 5,
        imageUrl: '/logos/react.svg',
        url: 'https://reactjs.org',
        name: 'React (Hooks)',
        tooltip: 'Knowledge level',
        description: 'I started using React around the same time as Node.js. I created this webpage to improve my knowledge of this technology.',
    },
    {
        code: 'redux-saga',
        enabled: true,
        main: false,
        level: 4,
        imageUrl: '/logos/redux-saga.svg',
        url: 'https://redux-saga.js.org',
        name: 'Redux and Saga',
        tooltip: 'Knowledge level',
        description: 'These two libraries are indispensable to build complex apps with React.',
    },
    {
        code: 'material',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/material.svg',
        url: 'https://material-ui.com',
        name: 'Material-UI',
        tooltip: 'Knowledge level',
        description: 'After a few months with Semantic UI, the extremely wide and cleanliness of Material-UI "imposed" its introduction.',
    },
    {
        code: 'mongodb',
        enabled: true,
        main: true,
        level: 4,
        imageUrl: '/logos/mongodb.svg',
        url: 'https://www.mongodb.com',
        name: 'MongoDB',
        tooltip: 'Knowledge level',
        description:
            'In order to complete the transition to current technologies, MongoDB is absolutely the DB that best fits a Node.js server (for flexibility and usage methodology).',
    },
    {
        code: 'java',
        enabled: true,
        main: false,
        level: 6,
        imageUrl: '/logos/java.svg',
        url: 'https://www.java.com',
        name: 'Java EE',
        tooltip: 'Knowledge level',
        description: 'Java is the language I mainly use since 2014, notwithstanding JavaScript in the last few years is taking over.',
    },
    {
        code: 'spring',
        enabled: true,
        main: true,
        level: 5,
        imageUrl: '/logos/spring.svg',
        url: 'https://spring.io',
        name: 'Spring Boot',
        tooltip: 'Knowledge level',
        description: 'Spring Boot (and Spring) is the framework for Java I have been using since 2014 to create web services.',
    },
    {
        code: 'maven',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/maven.svg',
        url: 'https://maven.apache.org',
        name: 'Maven',
        tooltip: 'Knowledge level',
        description: 'Since I started developing in Java Maven, has accompanied and helped me to manage the various projects.',
    },
    {
        code: 'hibernate',
        enabled: true,
        main: false,
        level: 4,
        imageUrl: '/logos/hibernate.svg',
        url: 'https://hibernate.org',
        name: 'Hibernate',
        tooltip: 'Knowledge level',
        description:
            'In my opinion Hibernate is the most complete library to access the database in Java, certainly the most complete that I have used.',
    },
    {
        code: 'oracle',
        enabled: true,
        main: true,
        level: 5,
        imageUrl: '/logos/oracle.svg',
        url: 'https://www.oracle.com',
        name: 'Oracle DB (SQL)',
        tooltip: 'Knowledge level',
        description: 'Oracle Database is the main database I have been using before MongoDB.',
    },
    {
        code: 'git',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/git.svg',
        url: 'https://git-scm.com',
        name: 'Git',
        tooltip: 'Knowledge level',
        description: 'Git... Can you really develop without it!?',
    },
    {
        code: 'rancher',
        enabled: true,
        main: true,
        level: 2,
        imageUrl: '/logos/rancher.svg',
        url: 'https://rancher.com',
        name: 'Rancher',
        tooltip: 'Knowledge level',
        description: 'I use Rancher (literally as user) to manage the deployed Apps.',
    },
    {
        code: 'docker',
        enabled: true,
        main: false,
        level: 3,
        imageUrl: '/logos/docker.svg',
        url: 'https://www.docker.com',
        name: 'Docker',
        tooltip: 'Knowledge level',
        description: 'I use Docker as user but I also work with it with my home server.',
    },
    {
        code: 'unraid',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/unraid.svg',
        url: 'https://unraid.net/',
        name: 'Unraid',
        tooltip: 'Unraid OS',
        description: 'Unraid is the OS of my home server.',
    },
    {
        code: 'raspberry',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/raspberry.svg',
        url: 'https://www.raspberrypi.org',
        name: 'Raspberry Pi',
        tooltip: 'Knowledge level',
        description:
            'I started using the Raspberry Pi to build my personal server. After establishing that the first approach was extremely positive, I have used it for other projects (the main one was the Arcade Cabinet).',
    },
    {
        code: 'arduino',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/arduino.svg',
        url: 'https://www.arduino.cc',
        name: 'Arduino',
        tooltip: 'Knowledge level',
        description: 'Arduino is more like one of my hobbies. I like being able to build small, low-cost circuits at home.',
    },
    {
        code: 'wordpress',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/wordpress.svg',
        url: 'https://wordpress.com',
        name: 'WordPress',
        tooltip: 'Knowledge level',
        description: 'In some cases the fastest, simplest and most immediate choice...',
    },
    {
        code: 'latex',
        enabled: true,
        main: false,
        level: 5,
        imageUrl: '/logos/latex.svg',
        url: 'https://www.latex-project.org',
        name: 'LaTeX',
        tooltip: 'Knowledge level',
        description: 'LaTeX is simply my favorite typesetting system!',
    },
];
